#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

mkdir -p docs

SPEC_JSON=$(python3 - <<'EOF'
import json, yaml
print(json.dumps(yaml.safe_load(open("openapi.yaml")), separators=(",", ":")))
EOF
)

cat > docs/api.html <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Invoice &amp; Payment Service — API Reference</title>
  <style>body { margin: 0; }</style>
</head>
<body>
  <!-- Generated by scripts/build-docs.sh from openapi.yaml. Do not edit by hand. -->
  <script id="api-spec" type="application/json">
${SPEC_JSON}
  </script>
  <div id="app"></div>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.67.0/dist/browser/standalone.min.js"></script>
  <script>
    Scalar.createApiReference('#app', {
      content: document.getElementById('api-spec').textContent,
      theme: 'kepler',
      hideDarkModeToggle: false,
      defaultOpenAllTags: false,
    });
  </script>
</body>
</html>
EOF

echo "wrote docs/api.html ($(wc -c < docs/api.html | tr -d ' ') bytes)"
